### ISSUE TITLE
token expires when page is refreshed. it shouldnt be the case!!!

### ISSUE THREAD

**Issue by naveenduttvyas** [nielsutrecht/jwt-angular-spring#4]
Hi, 

I used your library and it works fine. but problem is when I refresh the active page, Bearer token expires and it asks user again to login. How this can be avoided.

Also, when someone is trying to hit URL without login, you are showing fallback page? How did you configure that?

Thanks

**Comment by nielsutrecht** [comment]
Hi @naveenduttvyas,

The project is example code, not a 'library' or code you can just copy-paste. If you want to keep the token you will have to store it yourself client side in for example local storage.
