### ISSUE TITLE
Help: Exclude FilterRegistrationBean URL pattern  

### ISSUE THREAD

**Issue by warapitiya** [nielsutrecht/jwt-angular-spring#6]
Hi, I would really like to know is there a way to exclude an URL. For example

``` java
@Bean
    public FilterRegistrationBean jwtFilter() {
        final FilterRegistrationBean registrationBean = new FilterRegistrationBean();
        registrationBean.setFilter(new JwtFilter());
        registrationBean.addUrlPatterns("/api/*");

        //Remove the single URL
        registrationBean.removeUrlPatterns("/api/user"); //for post method only

        return registrationBean;
    }
```

Thanks.

**Comment by nielsutrecht** [comment]
As far as I know the Servlet spec does not support regular expressions. However what you can do in your Filter itself is doing a regular expression check on the route and just skip the JWT logic if it matches a certain route and method.
