### ISSUE TITLE
Error run in latest Spring Boot version

### ISSUE THREAD

**Issue by hendisantika** [nielsutrecht/jwt-angular-spring#8]
Nice repo.
But I have an error when I was runnin in latest Spring Boot version (1.5.3).
`mvn clean spring-boot:run`

Could you please upgrade to latest spring boot version so that you can see the errors too.

Thanks.

**Comment by nielsutrecht** [comment]
FilterRegistrationBean moved to org.springframework.boot.web.servlet in 1.4, this has now been fixed.
